name: Ruby

on: [push,pull_request]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: ruby:latest
    services:
      redis:
        image: redis

    steps:
    - uses: actions/checkout@v2
    - name: Run the default task
      run: |
        gem install bundler -v 2.2.3
        bundle install
        bundle exec rake
      env:
          # The hostname used to communicate with the Redis service container
          REDIS_HOST: redis
          REDIS_PORT: 6379
